=== amitkapps/pocs/Jaxp/src/main/java/test.xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.matson.com/schema/cas/cache"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.matson.com/schema/cas/cache" elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xsd:complexType name="lru-eviction-type">
        <xsd:attribute type="xsd:int" name="min-time-to-live-secs"/>
        <xsd:attribute type="xsd:int" name="time-to-idle-secs"/>
        <xsd:attribute type="xsd:int" name="max-time-to-live"/>
        <xsd:attribute type="xsd:int" name="max-node-count"/>
    </xsd:complexType>

    <xsd:complexType name="eviction-config-type">
        <xsd:choice>
            <xsd:element type="lru-eviction-type" name="lru-eviction"/>
            <xsd:element name="no-eviction"/>
        </xsd:choice>
    </xsd:complexType>

    <!-- top level <cas-cache> tag -->
    <xsd:element name="cas-cache">
        <xsd:complexType>
            <xsd:sequence minOccurs="1">
                <xsd:element type="eviction-config-type" name="default-eviction-config" minOccurs="0" maxOccurs="1"/>
                <xsd:element type="region-type" name="region" maxOccurs="unbounded" minOccurs="0"/>
            </xsd:sequence>
            <xsd:attribute name="application-root-node" use="required">
                <xsd:annotation>
                    <xsd:documentation>
                        The node for the application under which its cache regions will be
                        created.
                    </xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z_-]+"></xsd:pattern>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="region-type">
        <xsd:annotation>
            <xsd:documentation>
                A named region under which all the application's cached objects will be bound.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:choice>
                <xsd:element type="eviction-config-type" name="eviction-config"/>
            </xsd:choice>
        </xsd:sequence>
        <xsd:attribute type="xsd:ID" name="node-name" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== amitkapps/pocs/Jaxp/target/test-classes/test.xml
<cas-cache xmlns="http://www.matson.com/schema/cas/cache"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.matson.com/schema/cas/cache test.xml.xsd"
    application-root-node="CAS">

    <cache-mode>
        <cluster/>
    </cache-mode>
    
    <default-eviction-config>
        <lru-eviction min-time-to-live-secs="15"
                      max-time-to-live-secs="900"
                      max-node-count="1000"/>
    </default-eviction-config>

    <region node-name="search">
        <eviction-config>
            <no-eviction/>
        </eviction-config>
    </region>
    <region node-name="report">
        <eviction-config>
            <no-eviction/>
        </eviction-config>
    </region>
</cas-cache>
